/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 19 Mar 2026 17:29
*/
#define NBDirsMax 2
/* Small example to differentiate many dependent variables
 * with respect to a many independent variable. 
 * i.e. f: R^m \to R^n */
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <math.h>

#include <time.h>
typedef struct _pt {
    float x;
    float y;
    float z;
    float aff;
    /* Stands for affinity */
    int nb_neighbours;
} pt;
typedef struct _pt_diffv {
    float aff[NBDirsMax];
} pt_diffv;
typedef struct _connection {
    int idx1;
    int idx2;
    float d;
    struct _connection *next;
} connection;

float norm_pts_nodiff(pt pt1, pt pt2) {
    return (pt1.x-pt2.x)*(pt1.x-pt2.x) + (pt1.y-pt2.y)*(pt1.y-pt2.y) + (pt1.z-
    pt2.z)*(pt1.z-pt2.z);
}

/*
  Differentiation of compute_matrices in forward (tangent) mode (with options context multiDirectional):
   variations   of useful results: compute_matrices
   with respect to varying inputs: sigma max_val
   RW status of diff variables: compute_matrices:out sigma:in
                max_val:in A:(loc) S:(loc)
   Plus diff mem management of: pts:in A:in A[0:nb_pts-1]:in S:in
                S[0:nb_pts-1]:in
*/
void compute_matrices_dv(int nb_pts, float sigma, float sigmad[NBDirsMax], 
        float max_val, float max_vald[NBDirsMax], pt pts[nb_pts], pt_diffv 
        ptsd[nb_pts], connection *cnts, float A[nb_pts][nb_pts], float Ad[
        nb_pts][nb_pts][NBDirsMax], float S[nb_pts][nb_pts], float Sd[nb_pts][
        nb_pts][NBDirsMax], float *compute_matrices, float compute_matricesd[
        NBDirsMax], int nbdirs) {
    // Compute all distances and affinity
    float result1;
    float arg1;
    float arg1d[NBDirsMax];
    int nd;
    int ii2;
    int ii1;
    for (ii1 = 0; ii1 < nb_pts; ++ii1)
        for (ii2 = 0; ii2 < nb_pts; ++ii2)
            for (nd = 0; nd < NBDirsMax; ++nd)
                Ad[ii1][ii2][nd] = 0.0;
    for (ii1 = 0; ii1 < nb_pts; ++ii1)
        for (ii2 = 0; ii2 < nb_pts; ++ii2)
            for (nd = 0; nd < NBDirsMax; ++nd)
                Sd[ii1][ii2][nd] = 0.0;
    for (int i = 0; i < nb_pts; ++i) {
        float temp;
        for (int j = i+1; j < nb_pts; ++j) {
            result1 = norm_pts_nodiff(pts[i], pts[j]);
            temp = result1/(max_val*max_val);
            for (nd = 0; nd < nbdirs; ++nd) {
                Ad[i][j][nd] = -(temp*2*max_vald[nd]/max_val);
                Ad[j][i][nd] = Ad[i][j][nd];
            }
            A[i][j] = temp;
            A[j][i] = A[i][j];
            // printf("Normalized Distance between points %i and %i is %f\n", i, j, A[i][j]);
            temp = A[i][j]/sigma;
            arg1 = -temp;
            for (nd = 0; nd < nbdirs; ++nd) {
                arg1d[nd] = -((Ad[i][j][nd]-temp*sigmad[nd])/sigma);
                Sd[i][j][nd] = exp(arg1)*arg1d[nd];
                Sd[j][i][nd] = Sd[i][j][nd];
            }
            S[i][j] = exp(arg1);
            S[j][i] = S[i][j];
        }
    }
    for (ii1 = 0; ii1 < nb_pts; ++ii1)
        for (nd = 0; nd < NBDirsMax; ++nd)
            ptsd[ii1].aff[nd] = 0.0;
    // Go over all connections to compute and store their distances
    for (connection *conn = cnts; conn != (void *)0; conn = conn->next) {
        conn->d = A[conn->idx1][conn->idx2];
        for (nd = 0; nd < nbdirs; ++nd)
            ptsd[conn->idx1].aff[nd] = S[conn->idx1][conn->idx2]*ptsd[conn->
                idx1].aff[nd] + pts[conn->idx1].aff*Sd[conn->idx1][conn->idx2]
                [nd];
        pts[conn->idx1].aff *= S[conn->idx1][conn->idx2];
        for (nd = 0; nd < nbdirs; ++nd)
            ptsd[conn->idx2].aff[nd] = S[conn->idx1][conn->idx2]*ptsd[conn->
                idx2].aff[nd] + pts[conn->idx2].aff*Sd[conn->idx1][conn->idx2]
                [nd];
        pts[conn->idx2].aff *= S[conn->idx1][conn->idx2];
        pts[conn->idx1].nb_neighbours++;
        pts[conn->idx2].nb_neighbours++;
    }
    float aff;
    float affd[NBDirsMax];
    aff = 0;
    for (nd = 0; nd < NBDirsMax; ++nd)
        affd[nd] = 0.0;
    for (int i = 0; i < nb_pts; ++i) {
        for (nd = 0; nd < nbdirs; ++nd)
            affd[nd] = affd[nd] + 2*pts[i].aff*ptsd[i].aff[nd];
        aff += pts[i].aff*pts[i].aff;
    }
    *compute_matrices = aff;
    for (nd = 0; nd < nbdirs; ++nd)
        compute_matricesd[nd] = affd[nd];
}

/*
  Differentiation of main as a context to call tangent code (with options multiDirectional context):
*/
int main(int argc, char *argv[]) {
    int nb_pts;
    int nbdirs;
    nb_pts = 5;
    float sigma;
    float sigmad[NBDirsMax];
    sigma = 20.0;
    float max_val;
    float max_vald[NBDirsMax];
    max_val = 10.0;
    if (argc >= 2)
        sigma = atof(argv[1]);
    if (argc >= 3)
        max_val = atof(argv[2]);
    printf("sigma = %f \t -- \t max_val = %f\n", sigma, max_val);
    pt pts[nb_pts];
    pt_diffv ptsd[nb_pts];
    // First point
    pts[0].x = 1.0;
    pts[0].y = 1.0;
    pts[0].z = 1.0;
    pts[0].aff = 1;
    pts[0].nb_neighbours = 0;
    // Second point
    pts[1].x = 0.0;
    pts[1].y = 1.0;
    pts[1].z = 1.0;
    pts[1].aff = 1;
    pts[1].nb_neighbours = 0;
    // Third point
    pts[2].x = 0.0;
    pts[2].y = 0.0;
    pts[2].z = 1.0;
    pts[2].aff = 1;
    pts[2].nb_neighbours = 0;
    // Fourth point
    pts[3].x = -1.0;
    pts[3].y = -1.0;
    pts[3].z = 1.0;
    pts[3].aff = 1;
    pts[3].nb_neighbours = 0;
    // Fifth point
    pts[4].x = -1.0;
    pts[4].y = -1.0;
    pts[4].z = -1.0;
    pts[4].aff = 1;
    pts[4].nb_neighbours = 0;
    // Prepare the data for receiving affinity and similarity matrices
    float A[nb_pts][nb_pts], S[nb_pts][nb_pts];
    float Ad[nb_pts][nb_pts][NBDirsMax], Sd[nb_pts][nb_pts][NBDirsMax];
    for (int i = 0; i < nb_pts; ++i)
        for (int j = 0; j < nb_pts; ++j) {
            A[i][j] = 0;
            S[i][j] = 0;
        }
    connection *cnts;
    cnts = (void *)0;
    connection *next;
    next = (void *)0;
    for (int i = 0; i < nb_pts; ++i)
        for (int j = i + 1; j < nb_pts; j += i + 1) {
            cnts = (connection *)malloc(sizeof(connection));
            cnts->idx1 = i;
            cnts->idx2 = j;
            cnts->d = -1;
            // not computed yet
            cnts->next = next;
            next = cnts;
        }
    // Visual inspection of the data 
    for (next = cnts; next != (void *)0; next = next->next)
        printf("Looking at connection (%i, %i)\n", next->idx1, next->idx2);
    float aff;
    float affd[NBDirsMax];
    nbdirs = NBDirsMax;
    // Time things for 1000 of such computations to be compared with the vector mode
    // int nb_loops = 5; 
    int nb_loops = 1000; 
    float grad_aff[2] = {0.0,0.0};
    clock_t t = clock();
    for(int i=nb_loops+1; i>0; --i) {
        for(int p = 0; p < nb_pts; ++p) {
            pts[p].aff = 1.0;
        }
        sigmad[0] = 1.0;
        sigmad[1] = 0.0;
        max_vald[0] = 0.0;
        max_vald[1] = 1.0;
        compute_matrices_dv(nb_pts, sigma, sigmad, max_val, max_vald, pts, ptsd, 
                        cnts, A, Ad, S, Sd, &aff, affd, nbdirs);
        grad_aff[0] += affd[0];
        // printf("Trial %i. dAff/dSigma = %f\n", i, affd[0]);
        grad_aff[1] += affd[1];
    }
    t = clock() - t;
    printf("Average vector mode (over %i trials) Final gradient estimation is: dAff/dsigma = %f and dAff/dmax_val = %f\n", nb_loops, grad_aff[0]/nb_loops, grad_aff[1]/nb_loops);
    printf("%i runs in %f seconds.\n", nb_loops, ((double)t)/CLOCKS_PER_SEC);
    return 0;
}
