/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 19 Mar 2026 17:29
*/
#define NBDirsMax 4
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
#include <adStack.h>
/* Example of code highlighting the complexity of computing gradients in the presence of many inputs 
 * It shows the importance of both vector mode and reverse mode AD
 */
#include <stdio.h>
#include <math.h>

#include <time.h>
/*
  Differentiation of compute_avg in reverse (adjoint) mode (with options context standaloneDiff multiDirectional):
   gradient     of useful results: compute_avg values[0:n-1]
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_avg_bv(int n, double values[n], double valuesb[n][NBDirsMax], 
        double compute_avgb[NBDirsMax], int nbdirs) {
    double s;
    double sb[NBDirsMax];
    int nd;
    for (nd = 0; nd < nbdirs; ++nd)
        sb[nd] = compute_avgb[nd]/n;
    for (int i = 1; i < n; ++i)
        for (nd = 0; nd < nbdirs; ++nd)
            valuesb[i][nd] = valuesb[i][nd] + sb[nd];
    for (nd = 0; nd < nbdirs; ++nd)
        valuesb[0][nd] = valuesb[0][nd] + sb[nd];
}

double compute_avg_nodiff(int n, double values[n]) {
    double s;
    s = values[0];
    for (int i = n-1; i > 0; --i)
        s += values[i];
    return s/n;
}

/*
  Differentiation of compute_mean_abs_deviation in reverse (adjoint) mode (with options context standaloneDiff multiDirectional):
   gradient     of useful results: values[0:n-1] compute_mean_abs_deviation
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_mean_abs_deviation_bv(int n, double values[n], double valuesb[n][
        NBDirsMax], double compute_mean_abs_deviationb[NBDirsMax], int nbdirs)
{
    double avg;
    double avgb[NBDirsMax];
    double fabs0;
    double fabs0b[NBDirsMax];
    int branch;
    int nd;
    avg = compute_avg_nodiff(n, values);
    double s;
    double sb[NBDirsMax];
    if (values[0] - avg >= 0.0)
        pushControl1b(0);
    else
        pushControl1b(1);
    for (int i = n-1; i > 0; --i)
        if (values[i] - avg >= 0.0)
            pushControl1b(0);
        else
            pushControl1b(1);
    for (nd = 0; nd < nbdirs; ++nd)
        sb[nd] = compute_mean_abs_deviationb[nd]/n;
    for (nd = 0; nd < NBDirsMax; ++nd)
        avgb[nd] = 0.0;
    for (int i = 1; i < n; ++i) {
        for (nd = 0; nd < nbdirs; ++nd)
            fabs0b[nd] = sb[nd];
        popControl1b(&branch);
        if (branch == 0)
            for (nd = 0; nd < nbdirs; ++nd) {
                valuesb[i][nd] = valuesb[i][nd] + fabs0b[nd];
                avgb[nd] = avgb[nd] - fabs0b[nd];
            }
        else
            for (nd = 0; nd < nbdirs; ++nd) {
                avgb[nd] = avgb[nd] + fabs0b[nd];
                valuesb[i][nd] = valuesb[i][nd] - fabs0b[nd];
            }
    }
    popControl1b(&branch);
    if (branch != 0)
        goto label100;
    for (nd = 0; nd < nbdirs; ++nd) {
        valuesb[0][nd] = valuesb[0][nd] + sb[nd];
        avgb[nd] = avgb[nd] - sb[nd];
    }
    goto label110;
  label100:
    for (nd = 0; nd < nbdirs; ++nd) {
        avgb[nd] = avgb[nd] + sb[nd];
        valuesb[0][nd] = valuesb[0][nd] - sb[nd];
    }
  label110:
    compute_avg_bv(n, values, valuesb, avgb, nbdirs);
}

double compute_mean_abs_deviation_nodiff(int n, double values[n]) {
    double avg;
    double fabs0;
    avg = compute_avg_nodiff(n, values);
    double s;
    if (values[0] - avg >= 0.0)
        s = values[0] - avg;
    else
        s = -(values[0]-avg);
    for (int i = n-1; i > 0; --i) {
        if (values[i] - avg >= 0.0)
            fabs0 = values[i] - avg;
        else
            fabs0 = -(values[i]-avg);
        s += fabs(values[i] - avg);
    }
    return s/n;
}

/*
  Differentiation of compute_sq_norm in reverse (adjoint) mode (with options context standaloneDiff multiDirectional):
   gradient     of useful results: compute_sq_norm
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_sq_norm_bv(int n, double values[n], double valuesb[n][NBDirsMax],
        double compute_sq_normb[NBDirsMax], int nbdirs) {
    double s;
    double sb[NBDirsMax];
    int nd;
    for (nd = 0; nd < nbdirs; ++nd)
        sb[nd] = compute_sq_normb[nd];
    {
      int ii1;
      for (ii1 = 0; ii1 < n; ++ii1)
          for (nd = 0; nd < NBDirsMax; ++nd)
              valuesb[ii1][nd] = 0.0;
      for (int i = 1; i < n; ++i)
          for (nd = 0; nd < nbdirs; ++nd)
              valuesb[i][nd] = valuesb[i][nd] + 2*values[i]*sb[nd];
    }
    for (nd = 0; nd < nbdirs; ++nd)
        valuesb[0][nd] = valuesb[0][nd] + 2*values[0]*sb[nd];
}

double compute_sq_norm_nodiff(int n, double values[n]) {
    double s;
    s = values[0]*values[0];
    for (int i = n-1; i > 0; --i)
        s += values[i]*values[i];
    return s;
}

/*
  Differentiation of compute_std in reverse (adjoint) mode (with options context standaloneDiff multiDirectional):
   gradient     of useful results: compute_std
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_std_bv(int n, double values[n], double valuesb[n][NBDirsMax], 
        double compute_stdb[NBDirsMax], int nbdirs) {
    double avg;
    double avgb[NBDirsMax];
    int nd;
    double tempb[NBDirsMax];
    avg = compute_avg_nodiff(n, values);
    double nsq;
    double nsqb[NBDirsMax];
    nsq = compute_sq_norm_nodiff(n, values);
    for (nd = 0; nd < nbdirs; ++nd) {
        tempb[nd] = (nsq/n - avg*avg == 0.0 ? 0.0 : compute_stdb[nd]/(2.0*sqrt
            (nsq/n-avg*avg)));
        nsqb[nd] = tempb[nd]/n;
        avgb[nd] = -(2*avg*tempb[nd]);
    }
    compute_sq_norm_bv(n, values, valuesb, nsqb, nbdirs);
    compute_avg_bv(n, values, valuesb, avgb, nbdirs);
}

double compute_std_nodiff(int n, double values[n]) {
    double avg;
    avg = compute_avg_nodiff(n, values);
    double nsq;
    nsq = compute_sq_norm_nodiff(n, values);
    return sqrt(nsq/n - avg*avg);
}

/*
  Differentiation of abs_to_std in reverse (adjoint) mode (with options context standaloneDiff multiDirectional):
   gradient     of useful results: s abs_to_std a
   with respect to varying inputs: s a
*/
void abs_to_std_bv(double a, double (*ab)[NBDirsMax], double s, double (*sb)[
        NBDirsMax], double abs_to_stdb[NBDirsMax], int nbdirs) {
    double tempb[NBDirsMax];
    int nd;
    for (nd = 0; nd < nbdirs; ++nd) {
        tempb[nd] = abs_to_stdb[nd]/s;
        (*ab)[nd] = (*ab)[nd] + 2*a*tempb[nd];
        (*sb)[nd] = (*sb)[nd] - (2*s+(a*a-s*s)/s)*tempb[nd];
    }
}

double abs_to_std_nodiff(double a, double s) {
    return (a*a-s*s)/s;
}

/*
  Differentiation of compute_qoi in reverse (adjoint) mode (with options context standaloneDiff multiDirectional):
   gradient     of useful results: *std *a_to_s *average *mabs
   with respect to varying inputs: *std *a_to_s *average values[0:n-1]
                *mabs
   RW status of diff variables: std:(loc) *std:in-out a_to_s:(loc)
                *a_to_s:in-out average:(loc) *average:in-out values:(loc)
                values[0:n-1]:out mabs:(loc) *mabs:in-out
   Plus diff mem management of: std:in a_to_s:in average:in values:in
                mabs:in
*/
void compute_qoi_bv(int n, double values[n], double valuesb[n][NBDirsMax], 
        double *average, double (*averageb)[NBDirsMax], double *mabs, double (
        *mabsb)[NBDirsMax], double *std, double (*stdb)[NBDirsMax], double *
        a_to_s, double (*a_to_sb)[NBDirsMax], int nbdirs) {
    int nd;
    *mabs = compute_mean_abs_deviation_nodiff(n, values);
    *std = compute_std_nodiff(n, values);
    abs_to_std_bv(*mabs, mabsb, *std, stdb, *a_to_sb, nbdirs);
    for (nd = 0; nd < NBDirsMax; ++nd)
        (*a_to_sb)[nd] = 0.0;
    compute_std_bv(n, values, valuesb, *stdb, nbdirs);
    for (nd = 0; nd < NBDirsMax; ++nd)
        (*stdb)[nd] = 0.0;
    compute_mean_abs_deviation_bv(n, values, valuesb, *mabsb, nbdirs);
    for (nd = 0; nd < NBDirsMax; ++nd)
        (*mabsb)[nd] = 0.0;
    compute_avg_bv(n, values, valuesb, *averageb, nbdirs);
    for (nd = 0; nd < NBDirsMax; ++nd)
        (*averageb)[nd] = 0.0;
}

void compute_qoi_nodiff(int n, double values[n], double *average, double *mabs
        , double *std, double *a_to_s) {
    *average = compute_avg_nodiff(n, values);
    *mabs = compute_mean_abs_deviation_nodiff(n, values);
    *std = compute_std_nodiff(n, values);
    *a_to_s = abs_to_std_nodiff(*mabs, *std);
}

/*
  Differentiation of main as a context to call adjoint code (with options context standaloneDiff multiDirectional):
*/
int main(int argc, char *argv[]) {
    int n;
    int nbdirs = NBDirsMax;
    n = 200;
    double values[n];
    double valuesb[n][NBDirsMax];
    values[n - 1] = 32.01;
    // Fill some values
    for (int i = n - 1; i > 0; --i)
        values[i - 1] = 2.0*sqrt(values[i])*i + exp(-values[i]);
    double average, mabs, std, as;
    double averageb[NBDirsMax], mabsb[NBDirsMax], stdb[NBDirsMax], asb[
    NBDirsMax];

    int nb_loops = 1000;

    // Only keep track of the first 4 coordinates for printing
    double grad_avg[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_mabs[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_std[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_ats[4] = {0.0, 0.0, 0.0, 0.0};

    clock_t t = clock();
    for(int i=nb_loops; i > 0; --i){

        mabsb[0] = 0.0;
        mabsb[1] = 1.0;
        mabsb[2] = 0.0;
        mabsb[3] = 0.0;
        stdb[0] = 0.0;
        stdb[1] = 0.0;
        stdb[2] = 1.0;
        stdb[3] = 0.0;
        asb[0] = 0.0;
        asb[1] = 0.0;
        asb[2] = 0.0;
        asb[3] = 1.0;
        averageb[0] = 1.0;
        averageb[1] = 0.0;
        averageb[2] = 0.0;
        averageb[3] = 0.0;

        compute_qoi_bv(n, values, valuesb, &average, &averageb, &mabs, &mabsb, &
                   std, &stdb, &as, &asb, nbdirs);
        // Recover only the four first values for each one of these elements
        for(int j = 0; j < 4; ++j){
            grad_avg[j] += valuesb[j][0];
            grad_mabs[j] += valuesb[j][1];
            grad_std[j] += valuesb[j][2];
            grad_ats[j] += valuesb[j][3];
        }
    }
    t = clock() - t;
    printf("Average vector mode (over %i trials) Final Jacobian estimation is: \n", nb_loops); 
    printf("Grad avg:\t%f -- %f -- %f -- %f\n", grad_avg[0]/nb_loops, grad_avg[1]/nb_loops, grad_avg[2]/nb_loops, grad_avg[3]/nb_loops);
    printf("Grad mab:\t%f -- %f -- %f -- %f\n", grad_mabs[0]/nb_loops, grad_mabs[1]/nb_loops, grad_mabs[2]/nb_loops, grad_mabs[3]/nb_loops);
    printf("Grad std:\t%f -- %f -- %f -- %f\n", grad_std[0]/nb_loops, grad_std[1]/nb_loops, grad_std[2]/nb_loops, grad_std[3]/nb_loops);
    printf("Grad ats:\t%f -- %f -- %f -- %f\n", grad_ats[0]/nb_loops, grad_ats[1]/nb_loops, grad_ats[2]/nb_loops, grad_ats[3]/nb_loops);
    printf("%i runs in %f seconds.\n", nb_loops, ((double)t)/CLOCKS_PER_SEC);
    printf("Avg = %f\t Mean abs deviation = %f\t Standard deviation = %f\t Our metric = %f\n"
           , average, mabs, std, as);
}

int main_nodiff(int argc, char *argv[]) {
    int n;
    n = 200;
    double values[n];
    values[n - 1] = 32.01;
    // Fill some values
    for (int i = n - 1; i > 0; --i)
        values[i - 1] = 2.0*sqrt(values[i])*i + exp(-values[i]);
    double average, mabs, std, as;
    compute_qoi_nodiff(n, values, &average, &mabs, &std, &as);
    printf("Avg = %f\t Mean abs deviation = %f\t Standard deviation = %f\t Our metric = %f\n"
           , average, mabs, std, as);
}
