/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 19 Mar 2026 17:29
*/
/* Example of code highlighting the complexity of computing gradients in the presence of many inputs 
 * It shows the importance of both vector mode and reverse mode AD
 */
#include <stdio.h>
#include <math.h>

#include <time.h>

/**
 * Update the various useful piececs of code with generated differentiated code
 */

// Update here
// Make sure to change the function name in the cases of _dv, _b or _bv...
double compute_avg_d(int n, double values[n], double valuesd[n], double *
        compute_avg) {
    double s = values[0];
    double sd = valuesd[0];
    *compute_avg = s/n;
    return sd/n;
}

double compute_avg_nodiff(int n, double values[n]) {
    double s = values[0];
    for (int i = n-1; i > 0; --i)
        s += values[i];
    return s/n;
}


// Update here.
double compute_mean_abs_deviation_d(int n, double values[n], double valuesd[n]
        , double *compute_mean_abs_deviation) {
    double avg;
    double avgd;
    avgd = compute_avg_d(n, values, valuesd, &avg);
    double s;
    double sd;
    if (values[0] - avg >= 0.0) {
        sd = valuesd[0] - avgd;
        s = values[0] - avg;
    } else {
        sd = avgd - valuesd[0];
        s = -(values[0]-avg);
    }
    *compute_mean_abs_deviation = s/n;
    return sd/n;
}

double compute_mean_abs_deviation_nodiff(int n, double values[n]) {
    // Clearly, we can do better in computing everything, but this is not the point of the demonstration.
    double avg;
    double fabs0;
    avg = compute_avg_nodiff(n, values);
    double s;
    if (values[0] - avg >= 0.0)
        s = values[0] - avg;
    else
        s = -(values[0]-avg);
    for (int i = n-1; i > 0; --i) {
        if (values[i] - avg >= 0.0)
            fabs0 = values[i] - avg;
        else
            fabs0 = -(values[i]-avg);
        s += fabs(values[i] - avg);
    }
    return s/n;
}

// Update here
double compute_sq_norm_d(int n, double values[n], double valuesd[n], double *
        compute_sq_norm) {
    double s = values[0]*values[0];
    double sd = 2*values[0]*valuesd[0];
    *compute_sq_norm = s;
    return sd;
}

double compute_sq_norm_nodiff(int n, double values[n]) {
    double s = values[0]*values[0];
    for (int i = n-1; i > 0; --i)
        s += values[i]*values[i];
    return s;
}

// Update here
double compute_std_d(int n, double values[n], double valuesd[n], double *
        compute_std) {
    double result1;
    double result1d;
    result1d = valuesd[0];
    result1 = values[0];
    *compute_std = result1;
    return result1d;
}

double compute_std_nodiff(int n, double values[n]) {
    double avg;
    double arg1;
    double result1;
    avg = compute_avg_nodiff(n, values);
    double nsq;
    nsq = compute_sq_norm_nodiff(n, values);
    arg1 = nsq/n - avg*avg;
    result1 = sqrt(arg1);
    return result1;
}

// Update here
double abs_to_std_d(double a, double ad, double s, double sd, double *
        abs_to_std) {
    *abs_to_std = 2.0;
    return 3.0;
}

double abs_to_std_nodiff(double a, double s) {
    return (a*a-s*s)/s;
}

// Update here
void compute_qoi_d(int n, double values[n], double valuesd[n], double *average
        , double *averaged, double *mabs, double *mabsd, double *std, double *
        stdd, double *a_to_s, double *a_to_sd) {
    *averaged = 1.0;
    *mabsd = 2.0;
    *stdd = 3.0;
    *a_to_sd = 4.0;
}

void compute_qoi_nodiff(int n, double values[n], double *average, double *mabs
        , double *std, double *a_to_s) {
    *average = compute_avg_nodiff(n, values);
    *mabs = compute_mean_abs_deviation_nodiff(n, values);
    *std = compute_std_nodiff(n, values);
    *a_to_s = abs_to_std_nodiff(*mabs, *std);
}

/*
  Differentiation of main as a context to call tangent code (with options context standaloneDiff):
*/
int main(int argc, char *argv[]) {
    int n = 200;
    double values[n];
    double valuesd[n];
    for (int i=0; i < n; ++i) {
        valuesd[i] = 0.0;
    }
    double result1;
    values[n - 1] = 32.01;
    // Fill some values
    for (int i = n - 1; i > 0; --i) {
        result1 = sqrt(values[i]);
        values[i - 1] = 2.0*result1*i + exp(-values[i]);
    }
    double average, mabs, std, as;
    double averaged, mabsd, stdd, asd;
    int nb_loops = 1000;

    // Only keep track of the first 4 coordinates for printing
    double grad_avg[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_mabs[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_std[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_ats[4] = {0.0, 0.0, 0.0, 0.0};

    clock_t t = clock();
    for(int i=nb_loops; i > 0; --i){
        valuesd[0] = 0.0;
        valuesd[n-1] = 1.0;
        compute_qoi_d(n, values, valuesd, &average, &averaged, &mabs, &mabsd, &std
                      , &stdd, &as, &asd);
        // Continue with the computations and update the "gradients"
    }
    t = clock() - t;
    printf("Average hand made (over %i trials) Final Jacobian estimation is: \n", nb_loops); 
    printf("Grad avg:\t%f -- %f -- %f -- %f\n", grad_avg[0]/nb_loops, grad_avg[1]/nb_loops, grad_avg[2]/nb_loops, grad_avg[3]/nb_loops);
    printf("Grad mab:\t%f -- %f -- %f -- %f\n", grad_mabs[0]/nb_loops, grad_mabs[1]/nb_loops, grad_mabs[2]/nb_loops, grad_mabs[3]/nb_loops);
    printf("Grad std:\t%f -- %f -- %f -- %f\n", grad_std[0]/nb_loops, grad_std[1]/nb_loops, grad_std[2]/nb_loops, grad_std[3]/nb_loops);
    printf("Grad ats:\t%f -- %f -- %f -- %f\n", grad_ats[0]/nb_loops, grad_ats[1]/nb_loops, grad_ats[2]/nb_loops, grad_ats[3]/nb_loops);
    printf("%i runs in %f seconds.\n", nb_loops, ((double)t)/CLOCKS_PER_SEC);
    printf("Avg = %f\t Mean abs deviation = %f\t Standard deviation = %f\t Our metric = %f\n"
           , average, mabs, std, as);
}

int main_nodiff(int argc, char *argv[]) {
    int n = 200;
    double values[n];
    double result1;
    values[n - 1] = 32.01;
    // Fill some values
    for (int i = n - 1; i > 0; --i) {
        result1 = sqrt(values[i]);
        values[i - 1] = 2.0*result1*i + exp(-values[i]);
    }
    double average, mabs, std, as;
    compute_qoi_nodiff(n, values, &average, &mabs, &std, &as);
    printf("Avg = %f\t Mean abs deviation = %f\t Standard deviation = %f\t Our metric = %f\n"
           , average, mabs, std, as);
}
