/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (develop) - 19 Mar 2026 17:29
*/
#define NBDirsMax 200
/*  Hint: NBDirsMax should be the maximum number of differentiation directions
*/
/* Example of code highlighting the complexity of computing gradients in the presence of many inputs 
 * It shows the importance of both vector mode and reverse mode AD
 */
#include <stdio.h>
#include <math.h>

#include <time.h>
/*
  Differentiation of compute_avg in forward (tangent) mode (with options context standaloneDiff multiDirectional):
   variations   of useful results: compute_avg
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_avg_dv(int n, double values[n], double valuesd[n][NBDirsMax], 
        double *compute_avg, double compute_avgd[NBDirsMax], int nbdirs) {
    double s;
    double sd[NBDirsMax];
    int nd;
    for (nd = 0; nd < nbdirs; ++nd)
        sd[nd] = valuesd[0][nd];
    s = values[0];
    for (int i = n-1; i > 0; --i) {
        for (nd = 0; nd < nbdirs; ++nd)
            sd[nd] = sd[nd] + valuesd[i][nd];
        s += values[i];
    }
    *compute_avg = s/n;
    for (nd = 0; nd < nbdirs; ++nd)
        compute_avgd[nd] = sd[nd]/n;
}

double compute_avg_nodiff(int n, double values[n]) {
    double s;
    s = values[0];
    for (int i = n-1; i > 0; --i)
        s += values[i];
    return s/n;
}

/*
  Differentiation of compute_mean_abs_deviation in forward (tangent) mode (with options context standaloneDiff multiDirectional):
   variations   of useful results: compute_mean_abs_deviation
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_mean_abs_deviation_dv(int n, double values[n], double valuesd[n][
        NBDirsMax], double *compute_mean_abs_deviation, double 
        compute_mean_abs_deviationd[NBDirsMax], int nbdirs) {
    double avg;
    double avgd[NBDirsMax];
    double fabs0;
    double fabs0d[NBDirsMax];
    int nd;
    compute_avg_dv(n, values, valuesd, &avg, avgd, nbdirs);
    double s;
    double sd[NBDirsMax];
    if (values[0] - avg >= 0.0) {
        for (nd = 0; nd < nbdirs; ++nd)
            sd[nd] = valuesd[0][nd] - avgd[nd];
        s = values[0] - avg;
    } else {
        for (nd = 0; nd < nbdirs; ++nd)
            sd[nd] = avgd[nd] - valuesd[0][nd];
        s = -(values[0]-avg);
    }
    for (int i = n-1; i > 0; --i) {
        if (values[i] - avg >= 0.0) {
            for (nd = 0; nd < nbdirs; ++nd)
                fabs0d[nd] = valuesd[i][nd] - avgd[nd];
            fabs0 = values[i] - avg;
        } else {
            for (nd = 0; nd < nbdirs; ++nd)
                fabs0d[nd] = avgd[nd] - valuesd[i][nd];
            fabs0 = -(values[i]-avg);
        }
        for (nd = 0; nd < nbdirs; ++nd)
            sd[nd] = sd[nd] + fabs0d[nd];
        s += fabs(values[i] - avg);
    }
    *compute_mean_abs_deviation = s/n;
    for (nd = 0; nd < nbdirs; ++nd)
        compute_mean_abs_deviationd[nd] = sd[nd]/n;
}

double compute_mean_abs_deviation_nodiff(int n, double values[n]) {
    double avg;
    double fabs0;
    avg = compute_avg_nodiff(n, values);
    double s;
    if (values[0] - avg >= 0.0)
        s = values[0] - avg;
    else
        s = -(values[0]-avg);
    for (int i = n-1; i > 0; --i) {
        if (values[i] - avg >= 0.0)
            fabs0 = values[i] - avg;
        else
            fabs0 = -(values[i]-avg);
        s += fabs(values[i] - avg);
    }
    return s/n;
}

/*
  Differentiation of compute_sq_norm in forward (tangent) mode (with options context standaloneDiff multiDirectional):
   variations   of useful results: compute_sq_norm
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_sq_norm_dv(int n, double values[n], double valuesd[n][NBDirsMax],
        double *compute_sq_norm, double compute_sq_normd[NBDirsMax], int 
        nbdirs) {
    double s;
    double sd[NBDirsMax];
    int nd;
    for (nd = 0; nd < nbdirs; ++nd)
        sd[nd] = 2*values[0]*valuesd[0][nd];
    s = values[0]*values[0];
    for (int i = n-1; i > 0; --i) {
        for (nd = 0; nd < nbdirs; ++nd)
            sd[nd] = sd[nd] + 2*values[i]*valuesd[i][nd];
        s += values[i]*values[i];
    }
    *compute_sq_norm = s;
    for (nd = 0; nd < nbdirs; ++nd)
        compute_sq_normd[nd] = sd[nd];
}

double compute_sq_norm_nodiff(int n, double values[n]) {
    double s;
    s = values[0]*values[0];
    for (int i = n-1; i > 0; --i)
        s += values[i]*values[i];
    return s;
}

/*
  Differentiation of compute_std in forward (tangent) mode (with options context standaloneDiff multiDirectional):
   variations   of useful results: compute_std
   with respect to varying inputs: values[0:n-1]
   Plus diff mem management of: values:in
*/
void compute_std_dv(int n, double values[n], double valuesd[n][NBDirsMax], 
        double *compute_std, double compute_stdd[NBDirsMax], int nbdirs) {
    double avg;
    double avgd[NBDirsMax];
    double arg1;
    double arg1d[NBDirsMax];
    double result1;
    double result1d[NBDirsMax];
    int nd;
    double temp;
    compute_avg_dv(n, values, valuesd, &avg, avgd, nbdirs);
    double nsq;
    double nsqd[NBDirsMax];
    compute_sq_norm_dv(n, values, valuesd, &nsq, nsqd, nbdirs);
    arg1 = nsq/n - avg*avg;
    temp = sqrt(arg1);
    for (nd = 0; nd < nbdirs; ++nd) {
        arg1d[nd] = nsqd[nd]/n - 2*avg*avgd[nd];
        result1d[nd] = (arg1 == 0.0 ? 0.0 : arg1d[nd]/(2.0*temp));
        compute_stdd[nd] = result1d[nd];
    }
    result1 = temp;
    *compute_std = result1;
}

double compute_std_nodiff(int n, double values[n]) {
    double avg;
    double arg1;
    double result1;
    avg = compute_avg_nodiff(n, values);
    double nsq;
    nsq = compute_sq_norm_nodiff(n, values);
    arg1 = nsq/n - avg*avg;
    result1 = sqrt(arg1);
    return result1;
}

/*
  Differentiation of abs_to_std in forward (tangent) mode (with options context standaloneDiff multiDirectional):
   variations   of useful results: abs_to_std
   with respect to varying inputs: s a
*/
void abs_to_std_dv(double a, double ad[NBDirsMax], double s, double sd[
        NBDirsMax], double *abs_to_std, double abs_to_stdd[NBDirsMax], int 
        nbdirs) {
    int nd;
    double temp;
    temp = (a*a-s*s)/s;
    *abs_to_std = temp;
    for (nd = 0; nd < nbdirs; ++nd)
        abs_to_stdd[nd] = (2*a*ad[nd]-(2*s+temp)*sd[nd])/s;
}

double abs_to_std_nodiff(double a, double s) {
    return (a*a-s*s)/s;
}

/*
  Differentiation of compute_qoi in forward (tangent) mode (with options context standaloneDiff multiDirectional):
   variations   of useful results: *std *a_to_s *average *mabs
   with respect to varying inputs: values[0:n-1]
   RW status of diff variables: std:(loc) *std:out a_to_s:(loc)
                *a_to_s:out average:(loc) *average:out values:(loc)
                values[0:n-1]:in mabs:(loc) *mabs:out
   Plus diff mem management of: std:in a_to_s:in average:in values:in
                mabs:in
*/
void compute_qoi_dv(int n, double values[n], double valuesd[n][NBDirsMax], 
        double *average, double (*averaged)[NBDirsMax], double *mabs, double (
        *mabsd)[NBDirsMax], double *std, double (*stdd)[NBDirsMax], double *
        a_to_s, double (*a_to_sd)[NBDirsMax], int nbdirs) {
    compute_avg_dv(n, values, valuesd, average, *averaged, nbdirs);
    compute_mean_abs_deviation_dv(n, values, valuesd, mabs, *mabsd, nbdirs);
    compute_std_dv(n, values, valuesd, std, *stdd, nbdirs);
    abs_to_std_dv(*mabs, *mabsd, *std, *stdd, a_to_s, *a_to_sd, nbdirs);
}

void compute_qoi_nodiff(int n, double values[n], double *average, double *mabs
        , double *std, double *a_to_s) {
    *average = compute_avg_nodiff(n, values);
    *mabs = compute_mean_abs_deviation_nodiff(n, values);
    *std = compute_std_nodiff(n, values);
    *a_to_s = abs_to_std_nodiff(*mabs, *std);
}

/*
  Differentiation of main as a context to call tangent code (with options context standaloneDiff multiDirectional):
*/
int main(int argc, char *argv[]) {
    int n;
    double result1;
    int nbdirs = NBDirsMax;
    n = 200;
    double values[n];
    double valuesd[n][NBDirsMax];
    // Make sure you pass in the identity matrix
    for (int i=0; i < n; ++i) {
        for (int nd = 0; nd < NBDirsMax; ++nd) {
            valuesd[i][nd] = 0.0;
        }
        valuesd[i][i] = 1.0;
    }
    values[n - 1] = 32.01;
    // Fill some values
    for (int i = n - 1; i > 0; --i) {
        result1 = sqrt(values[i]);
        values[i - 1] = 2.0*result1*i + exp(-values[i]);
    }
    double average, mabs, std, as;
    double averaged[NBDirsMax], mabsd[NBDirsMax], stdd[NBDirsMax], asd[
    NBDirsMax];
    int nb_loops = 1000;

    // Only keep track of the first 4 coordinates for printing
    double grad_avg[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_mabs[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_std[4] = {0.0, 0.0, 0.0, 0.0};
    double grad_ats[4] = {0.0, 0.0, 0.0, 0.0};

    clock_t t = clock();
    for(int i=nb_loops; i > 0; --i){
        compute_qoi_dv(n, values, valuesd, &average, &averaged, &mabs, &mabsd, &
                   std, &stdd, &as, &asd, nbdirs);
        // Recover only the four first values for each one of these elements
        for(int j = 0; j < 4; ++j){
            grad_avg[j] += averaged[j];
            grad_mabs[j] += mabsd[j];
            grad_std[j] += stdd[j];
            grad_ats[j] += asd[j];
        }
    }
    t = clock() - t;
    printf("Average vector mode (over %i trials) Final Jacobian estimation is: \n", nb_loops); 
    printf("Grad avg:\t%f -- %f -- %f -- %f\n", grad_avg[0]/nb_loops, grad_avg[1]/nb_loops, grad_avg[2]/nb_loops, grad_avg[3]/nb_loops);
    printf("Grad mab:\t%f -- %f -- %f -- %f\n", grad_mabs[0]/nb_loops, grad_mabs[1]/nb_loops, grad_mabs[2]/nb_loops, grad_mabs[3]/nb_loops);
    printf("Grad std:\t%f -- %f -- %f -- %f\n", grad_std[0]/nb_loops, grad_std[1]/nb_loops, grad_std[2]/nb_loops, grad_std[3]/nb_loops);
    printf("Grad ats:\t%f -- %f -- %f -- %f\n", grad_ats[0]/nb_loops, grad_ats[1]/nb_loops, grad_ats[2]/nb_loops, grad_ats[3]/nb_loops);
    printf("%i runs in %f seconds.\n", nb_loops, ((double)t)/CLOCKS_PER_SEC);
    printf("Avg = %f\t Mean abs deviation = %f\t Standard deviation = %f\t Our metric = %f\n"
           , average, mabs, std, as);;
}

int main_nodiff(int argc, char *argv[]) {
    int n;
    double result1;
    n = 200;
    double values[n];
    values[n - 1] = 32.01;
    // Fill some values
    for (int i = n - 1; i > 0; --i) {
        result1 = sqrt(values[i]);
        values[i - 1] = 2.0*result1*i + exp(-values[i]);
    }
    double average, mabs, std, as;
    compute_qoi_nodiff(n, values, &average, &mabs, &std, &as);
    printf("Avg = %f\t Mean abs deviation = %f\t Standard deviation = %f\t Our metric = %f\n"
           , average, mabs, std, as);
}
